#!/bin/bash

set -e
set -o pipefail

if [ -z ${CIRCLECI+x} ]; then
    echo "Not on Circle; refusing to run."
    exit 1
fi

# Generate npmrc
echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
chmod 0600 .npmrc

# Bump to tag version
npm version "$CIRCLE_TAG" --no-git-tag-version

# Publish
npm publish --access public
